[server]
  port = ""

[andy.b]
    name = "b"
    url = "https://test.com"
    merchant_id = "asd"
    api_key = "zxc"

[andy.j]
    name = "j"
    url = "https://test.com"
    merchant_id = "fgh"
    api_key = "vbn"

[andy.i]
    name = "i"
    url = "https://test.com"
    merchant_id = "jkl"
    api_key = "mnb"
    order_api_key = "qwe"

[andy.wallet]
    vault2_address = "zxc"

[andy.telegram]
    chat_id = "12345"
    critical_chat_id = "12345"
    bot_token = "123:asd-zxc"
    vault2_bot_token = "123:asd-zxc"
    order_bot_token = "123:asd-zxc"

[andy.energy]
    url = "https://test.com"
    token = "asd"
    secret = "qwe"

[database]
    host = "127.0.0.1"
    port = "3306"
    user = "root"
    password = ""
    dbname = "tron"

[quicknode]
    api_key = "asd"
    app_id = "zxc"
    quick_alert_id = "zxc"

[tron]
    energy_address = ""
    private_key = ""